tc_parking:
    resource: "@TCParkingBundle/Resources/config/routing.yml"
    prefix:   /parkingplat

tc_platform:
    resource: "@TCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform
