tc_platform_home:
    path:      /{page}
    defaults:
        _controller: TCPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

tc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: TCPlatformBundle:Advert:view
    requirements:
        id: \d+

tc_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults:
        _controller: TCPlatformBundle:Advert:viewSlug
        _format:     html
    requirements:
        year:   \d{4}
        format: html|xml

tc_platform_add:
    path:      /add
    defaults:
        _controller: TCPlatformBundle:Advert:add

tc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: TCPlatformBundle:Advert:edit
    requirements:
        id: \d+

tc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: TCPlatformBundle:Advert:delete
    requirements:
        id: \d+

tc_platform_home2:
    path:      /test
    defaults:
        _controller: TCPlatformBundle:Advert:index2
